// Generated by CoffeeScript 1.9.3
(function() {
  var findFirst, init_radio, initializing, radio, start_stream, stop_stream, turned_on;

  initializing = false;

  radio = null;

  turned_on = false;

  chrome.browserAction.onClicked.addListener(function(tab) {
    if (radio != null) {
      if (turned_on) {
        stop_stream();
      } else {
        start_stream();
      }
    } else {
      if (!initializing) {
        init_radio("http://mp3-live.swr3.de/swr3_s.m3u", start_stream);
      }
    }
    return turned_on = !turned_on;
  });

  init_radio = function(url, callback) {
    initializing = true;
    return jQuery.get(url, function(content) {
      var actual_url, lines, radio_tmp;
      lines = content.split("\n");
      actual_url = findFirst(lines, function(string) {
        return string.indexOf("#") !== 0;
      });
      radio_tmp = document.createElement('audio');
      radio_tmp.setId;
      radio_tmp.setAttribute('src', actual_url);
      radio = radio_tmp;
      initializing = false;
      return callback();
    });
  };

  findFirst = function(array, predicate) {
    var elem, i, len;
    for (i = 0, len = array.length; i < len; i++) {
      elem = array[i];
      if (predicate(elem)) {
        return elem;
      }
    }
  };

  start_stream = function() {
    return radio.play();
  };

  stop_stream = function() {
    return radio.pause();
  };

}).call(this);
